notifications:
  email:
    - deepdive-dev@lists.stanford.edu
language:
  - scala
  - python
scala:
  - "2.10.5"
sbt_args:
jdk:
  - openjdk7
python:
  - "2.7"
services:
  - postgresql

cache:
  directories:
    - $HOME/.ivy2/cache

env:
  global:
    - PGUSER: postgres
    - PGPASSWORD:
    - PGPORT: 5432
    - PGHOST: localhost
    - DBNAME: deepdive_test
  matrix: # NOTE we're on a paid plan that gives us 2 parallel jobs
      # 1. Unit tests with PostgreSQL and integration tests with MySQL
    - TEST_ONLY: "'test/postgresql/scalatests.bats test/mysql/*.bats'"
      TEST_EXCEPT: test/mysql/scalatests.bats
      # 2. More integration tests with PostgreSQL
    - TEST_ONLY:
      TEST_EXCEPT: "'test/postgresql/scalatests.bats test/mysql/*.bats'"

before_install:
  # Check coding style before performing the build and tests
  - make checkstyle

install:
  - make depends
  - util/install.sh postgres
  - make test-build  # XXX doing it here to hide the noise from sbt and unzip

script:
  # Run all tests
  - make test

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

after_success:
  # Report test coverage
  - sbt coverageReport coveralls
