sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/
notifications:
  email:
    - deepdive-notifications@cs.stanford.edu
    # XXX Routing notifications through cs.stanford.edu as Travis cannot directly send to googlegroups.com
    # See: https://github.com/travis-ci/travis-ci/issues/2513
    #- deepdive-dev@googlegroups.com
  webhooks:
    urls:
      # gitter.im/HazyResearch/deepdive
      - https://webhooks.gitter.im/e/ee3a2470727e53cdc3c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
language:
  - scala
  - cpp
  - c
  - python
scala:
  - "2.11.7"
jdk:
  - oraclejdk8
python:
  - "2.7"
services:
  - postgresql

cache:
  directories:
    - .build
    - .github-release-assets
    - $HOME/.ivy2/cache

env:
  global:
    - PGUSER: postgres
    - PGPASSWORD:
    - PGPORT: 5432
    - PGHOST: localhost
    - DBNAME: deepdive_test
# Parallel jobs aren't effective since the `install` step currently takes most of the time.
#  matrix: # NOTE we're on a paid plan that gives us 2 parallel jobs
#      # 1. Unit tests with PostgreSQL and integration tests with MySQL
#    - TEST_ONLY: "'test/postgresql/scalatests.bats test/mysql/*.bats'"
#      TEST_EXCEPT: test/mysql/scalatests.bats
#      # 2. More integration tests with PostgreSQL
#    - TEST_ONLY:
#      TEST_EXCEPT: "'test/postgresql/scalatests.bats test/mysql/*.bats'"

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  # Check coding style before performing the build and tests
  - make checkstyle
  # Decrypt credentials for util/build/update-github-tags and update-github-release-asset
  - openssl aes-256-cbc -K $encrypted_54046ad4fea4_key -iv $encrypted_54046ad4fea4_iv -in .travis.tar.enc -out .travis.tar -d
  - tar xpvf .travis.tar
  - ln -sfnv "$PWD"/.travis/.{netrc,gist} ~/
  - chmod go= ~/.{netrc,gist}

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test  # for gcc 4.8
    packages:
    - python3
    - gnuplot
    - bc
    - bzip2
      # for building sampler
    - libnuma-dev
    - gcc-4.8
    - g++-4.8
      # for ddlog
    - oracle-java8-installer
      # for mindbender
    - ed

install:
#  - make depends # XXX does not work on container-based infra
  - jdk_switcher use oraclejdk8
  - export CXX="g++-4.8" CC="gcc-4.8" # necessary for building sampler
  - make test-build

script:
  # Run all tests
  - make test

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

# update GitHub releases for some select branches (master and v*.*.x)
deploy:
  - provider: script
    script: util/build/update-github-release-asset
    skip_cleanup: true
    on:
      repo: HazyResearch/deepdive
      all_branches: true
      # TODO condition: "$TRAVIS_BRANCH = master || $TRAVIS_BRANCH = v*.*.x"
  - provider: script
    script: util/build/update-github-release-asset
    skip_cleanup: true
    on:
      repo: HazyResearch/deepdive
      tag: true
