language: scala
scala:
  - "2.10.3"
jdk:
  - openjdk7
  - oraclejdk7
sbt_args:
services:
  - postgresql
before_script:
  - psql -c 'create database deepdive_test;' -U postgres
  # - psql -c 'create database deepdive_test;' -U postgres
env: 
  global:
    - PGUSER=postgres
    - PGPASSWORD=""
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test
    - PGDATABASE=deepdive_test
notifications:
  email:
    - deepdive-dev@lists.stanford.edu
script: "./test.sh"