language: 
  - scala
  - python
scala:
  - "2.10.3"
python:
  - "2.7"
install: 
  - sudo pip install linkchecker --use-mirrors
jdk:
  - openjdk7
  - oraclejdk7
sbt_args:
services:
  - postgresql
env: 
  global:
    - PGUSER=postgres
    - PGPASSWORD=""
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test
    - LD_LIBRARY_PATH=/tmp/dw_linux/lib/dw_linux/lib:/tmp/dw_linux/lib/dw_linux/lib64
notifications:
  email:
    - deepdive-dev@lists.stanford.edu
before_script:
  - unzip lib/dw_linux.zip -d /tmp/
  - psql -c 'create database deepdive_test;' -U postgres
  # - psql -c 'create database deepdive_test;' -U postgres
script: 
  - bash ./src/test/bash/linkcheck.sh
  - ./test.sh
