# Travis CI config to run tests using Docker
# See: https://docs.travis-ci.com/user/docker/
# See: https://docker.io/
sudo: required
dist: trusty
language: c  # C seems to have the least amount of setup
services:
  - docker

notifications:
  email:
    - deepdive-notifications@cs.stanford.edu
    # XXX Routing notifications through cs.stanford.edu as Travis cannot directly send to googlegroups.com
    # See: https://github.com/travis-ci/travis-ci/issues/2513
    #- deepdive-dev@googlegroups.com
  webhooks:
    urls:
      # gitter.im/HazyResearch/deepdive
      - https://webhooks.gitter.im/e/ee3a2470727e53cdc3c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  # Check coding style before performing the build and tests
  - make checkstyle;

  # Have Docker build scripts use and update the correct images
  - export DOCKER_IMAGE=netj/deepdive-build;
    export DOCKER_IMAGE_MASTER=$DOCKER_IMAGE:master;
    export DOCKER_IMAGE_TEST_PREFIX=$DOCKER_IMAGE:travis.$TRAVIS_JOB_NUMBER-${TRAVIS_COMMIT:0:7}-test.;

  # Pull Docker images
  - docker pull $DOCKER_IMAGE_MASTER;
  - docker pull postgres;

install:
  # Build using Docker
  - make build--in-container;
  # TODO tag the $DOCKER_IMAGE with TRAVIS environment

script:
  # Run all tests using Docker
  - make test--in-container;

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

after_script:
    # decide which test result image to push
  - DOCKER_IMAGE_TO_PUSH=$DOCKER_IMAGE_TEST_PREFIX;
    if [[ $TRAVIS_TEST_RESULT = 0 ]];
    then DOCKER_IMAGE_TO_PUSH+=PASS;
    else DOCKER_IMAGE_TO_PUSH+=FAIL;
    fi;
    # decide what tag to use
  - if [[ $TRAVIS_PULL_REQUEST = false ]];
    then tag=travis.$TRAVIS_BRANCH;
    else tag=travis-pr$TRAVIS_PULL_REQUEST;
    fi;
    tag=$(echo -n "$tag" | tr -c 'A-Za-z0-9_.-' _);

    # push the test result
  - docker login -e "$encrypted_DOCKER_EMAIL" -u "$encrypted_DOCKER_USERNAME" -p "$encrypted_DOCKER_PASSWORD";
  - docker tag $DOCKER_IMAGE_TO_PUSH $DOCKER_IMAGE:$tag;
    docker push $DOCKER_IMAGE:$tag;

    # update the master image with the successful build
  - case $TRAVIS_EVENT_TYPE-$TRAVIS_BRANCH-$TRAVIS_TEST_RESULT in
        push-master-0)
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE_MASTER;
            docker push $DOCKER_IMAGE_MASTER ;;
    esac;

## update GitHub releases for some select branches (master and v*.*.x)
#deploy:
#  - provider: script
#    script: util/build/decrypt-travis-then-update-github-releases
#    skip_cleanup: true
#    on:
#      repo: HazyResearch/deepdive
#      all_branches: true
#      # TODO condition: "$TRAVIS_BRANCH = master || $TRAVIS_BRANCH = v*.*.x"
#  - provider: script
#    script: util/build/decrypt-travis-then-update-github-releases
#    skip_cleanup: true
#    on:
#      repo: HazyResearch/deepdive
#      tag: true
