notifications:
  email:
    - deepdive-dev@googlegroups.com

sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7  # for clang-format-3.7
    - ubuntu-toolchain-r-test     # for gcc 4.8
    packages:
    - clang-format-3.7
    # for building sampler
    - libnuma-dev
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    # dependencies
    - lib/gtest
    - lib/gtest-1.7.0
    - lib/tclap

language: cpp
compiler:
  - gcc

before_install:
  # code should be already formatted
  - make format CLANG_FORMAT=clang-format-3.7
  - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  # skip preparing dependencies if they're cached
  - test -e lib/gtest/libgtest.a -a -e lib/gtest-1.7.0/include/gtest/gtest.h -a -d lib/tclap/include/tclap || make dep
  - make
script: make test
