notifications:
  email:
    - deepdive-dev@lists.stanford.edu
language:
  - scala
  - python
scala:
  - "2.10.5"
sbt_args:
jdk:
  - openjdk7
python:
  - "2.7"
services:
  - postgresql

cache:
  directories:
    - $HOME/.ivy2/cache

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test
  matrix:
      # unit tests
    - TEST_ONLY=test/*/scalatests.bats
      # PostgreSQL integration tests
    - TEST_ONLY=test/postgresql/*.bats  TEST_EXCEPT=test/*/scalatests.bats
      # MySQL integration tests
    - TEST_ONLY=test/mysql/*.bats  TEST_EXCEPT=test/*/scalatests.bats

before_install:
  # Check coding style before performing the build and tests
  - make checkstyle

install:
  - make depends
  - util/install.sh postgres
  - make test-build  # XXX doing it here to hide the noise from sbt and unzip

script:
  # Run all tests
  - make test

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

after_success:
  # Report test coverage
  - sbt coverageReport coveralls
