notifications:
  email:
    - deepdive-dev@lists.stanford.edu
language:
  - scala
  - python
scala:
  - "2.10.5"
sbt_args:
jdk:
  - openjdk7
  - oraclejdk7
python:
  - "2.7"
services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=
    - PGPORT=5432
    - PGHOST=localhost
    - DBNAME=deepdive_test

install:
  - make depends
  - util/install.sh postgres

before_script:
  # Check coding style before performing the build and tests
  - make checkstyle

script:
  # Run all tests
  - make test

  # Check broken links in documentation
  # TODO check only when doc/ has changed
  #- make -C doc/ linkcheck

after_success:
  # Report test coverage
  - sbt coverageReport coveralls
